sonar.projectKey=movie-catalog-ui
sonar.organization=enesakyel
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.exclusions=src/**/*.spec.ts

sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/movie-catalog-ui/lcov.info
sonar.sourceEncoding=UTF-8
